apiVersion: v1
kind: Pod
metadata:
  annotations:
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/cpu-request: 1000m
    gke-gcsfuse/memory-request: 3Gi
  labels:
    run: ffmpeg
  name: ffmpeg
  namespace: cooking
spec:
  serviceAccountName: mediamtx
  containers:
  - image:  asia-northeast1-docker.pkg.dev/jaguer-park-champion-demo/jaguer-winter/ffmpeg:v1.0
    command : ["/bin/sh","-c","sleep 100000"]
    name: ffmpeg
    resources:
      requests:
        cpu: 1000m
        memory: 3Gi
    volumeMounts:
      - name: gcs-fuse-csi-static
        mountPath: /data
  volumes:
    - name: gcs-fuse-csi-static
      persistentVolumeClaim:
        claimName: gcs-fuse-csi-static-pvc