apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-fuse-csi-pv-cooking
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  storageClassName: example-storage-class
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: jaguer-park-champion-demo-test-kamiya
    volumeAttributes:
      gcsfuseLoggingSeverity: warning

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-fuse-csi-static-pvc
  namespace: cooking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: gcs-fuse-csi-pv-cooking
  storageClassName: example-storage-class