apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediamtx
  name: mediamtx
  namespace: cooking
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/load-balancer-ip-addresses: "mediamtx"
spec:
  ports:
  - port: 1935
    protocol: TCP
    targetPort: 1935
    name: rtmp
  - port: 8554
    protocol: TCP
    targetPort: 8554
    name: rtsp
  type: LoadBalancer
  selector:
    app: mediamtx
